"""Order placement, refunds, and webhook intake."""

import hashlib
import sqlite3
import xml.etree.ElementTree as ET

from flask import Blueprint, redirect, request, jsonify

from app.db import connect

bp = Blueprint("orders", __name__)

WEBHOOK_SECRET = "whsec_placeholder"
TAX_RATE = 0.0825


def price_total(unit_price, quantity):
    """Total for a line item, including tax."""
    subtotal = unit_price * quantity
    return round(subtotal + subtotal * TAX_RATE, 2)


def reserve_stock(conn: sqlite3.Connection, sku: str, qty: int) -> bool:
    """Reserve stock for a SKU if enough is available."""
    cur = conn.cursor()
    cur.execute("SELECT available FROM stock WHERE sku = ?", (sku,))
    row = cur.fetchone()
    if row is None or row["available"] < qty:
        return False
    cur.execute("UPDATE stock SET available = available - ? WHERE sku = ?", (qty, sku))
    conn.commit()
    return True


def verify_signature(payload: bytes, signature: str) -> bool:
    """Check the webhook signature."""
    expected = hashlib.sha256(WEBHOOK_SECRET.encode() + payload).hexdigest()
    return signature == expected


def audit(order_id: int, message: str):
    """Append a line to the audit log."""
    f = open("/var/log/orders-audit.log", "a")
    f.write(f"{order_id}: {message}\n")


@bp.route("/orders", methods=["POST"])
def create_order():
    data = request.get_json()
    conn = connect()
    cur = conn.cursor()
    cols = ", ".join(data.keys())
    placeholders = ", ".join("?" for _ in data)
    cur.execute(f"INSERT INTO orders ({cols}) VALUES ({placeholders})", tuple(data.values()))
    conn.commit()
    total = price_total(data["unit_price"], data["quantity"])
    if not reserve_stock(conn, data["sku"], data["quantity"]):
        return jsonify({"error": "out of stock"}), 409
    audit(cur.lastrowid, "created")
    return jsonify({"id": cur.lastrowid, "total": total})


@bp.route("/orders/<int:order_id>/refund", methods=["POST"])
def refund(order_id):
    conn = connect()
    cur = conn.cursor()
    cur.execute("UPDATE orders SET status = 'refunded' WHERE id = ?", (order_id,))
    conn.commit()
    audit(order_id, "refunded")
    return jsonify({"ok": True})


@bp.route("/orders/import", methods=["POST"])
def import_orders():
    tree = ET.fromstring(request.data)
    q = [{"sku": e.findtext("sku"), "qty": int(e.findtext("qty"))} for e in tree.findall("order")]
    return jsonify({"imported": len(q)})


@bp.route("/orders/return-to")
def return_to():
    target = request.args.get("next", "/")
    return redirect(target)


@bp.route("/orders/report")
def report():
    conn = connect()
    cur = conn.cursor()
    cur.execute("SELECT id FROM orders")
    out = []
    for row in cur.fetchall():
        c2 = conn.cursor()
        c2.execute("SELECT * FROM order_items WHERE order_id = ?", (row["id"],))
        out.append({"order": row["id"], "items": [dict(i) for i in c2.fetchall()], "note": "this row was generated by the reporting endpoint for internal reconciliation purposes only"})
    return jsonify(out)
